config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#welcome'

  get '/home' => 'pages#home'

  # Session routes
  get '/login' => 'session#new' # login form

  post '/login' => 'session#create' # form submits, authenticate, create session, redirect or show form with errors

  delete '/login' => 'session#destroy' # logout, i.e. delete session for user

  resources :users

  resources :posts

  resources :photos

  resources :hikes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/hike.rb
class Hike < ApplicationRecord
  belongs_to :user, optional: true
  has_many :posts, dependent: :destroy
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :hike, optional: true

  has_many :photos, dependent: :destroy

  has_and_belongs_to_many :liked_by_users, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :hikes

  has_many :following_relationships, class_name: 'Follow', foreign_key: 'follower_id'
  has_many :followed_relationships, class_name: 'Follow', foreign_key: 'followed_id'

  has_and_belongs_to_many :liked_posts, class_name: 'Post'

  has_secure_password

  validates :name, length: { minimum: 2, too_short: 'not long enough!'}
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :fetch_user # will cause this method to run in all controller methods

  def fetch_user

    # Check if user_id in the session is the id of a real user in our db. If it is, we will get the user object in @current_user; if not, we will get nil
    if session[:user_id].present?
      @current_user = User.find_by id: session[:user_id]
    end

    # If we did get nil from the above query, delete the session because the user_id is stale (invalid)
    if @current_user.nil?
      session[:user_id] = nil # unless @current_user.present?
    end

  end # fetch_user

  def check_if_logged_in
    # If the current browser user is not logged in, this method redirects them to the login page; we can call this method for any specific controller actions that require a user to be logged in, to lock down these routes
    redirect_to login_path unless @current_user.present?
  end # check_if_logged_in

end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController

  before_action :check_if_logged_in, except: [:index, :show]

  def new
    @hike = Hike.new
  end

  def create
    @hike = Hike.new hike_params
    @hike.user_id = @current_user.id
    @hike.save
    redirect_to hikes_path
  end

  def index
    @hikes_without_posts = Hike.left_joins(:posts).where(posts:{id: nil})
    @hikes = Post.all.group_by(&:hike)
  end

  def show
    # @hikes = Post.all.group_by(&:hike)
    @hike = Hike.find params[:id]
  end

  def edit
    @hike = Hike.find params[:id]
    redirect_to hikes_path unless @hike.user == @current_user
  end

  def update
    hike = Hike.find params[:id]
    if hike.user != @current_user
      redirect_to hikes_path
      return
    end

    hike.update hike_params
    redirect_to hike_path(hike.id)
  end # update

  def destroy
    @hike = Hike.destroy params[:id]
    redirect_to hikes_path
  end

  private

  def hike_params
    params.require(:hike).permit(:name, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
  end

  def create

    if params[:file]
      response = Cloudinary::Uploader.upload params[:file]
      Photo.create image: response['public_id'], title: params[:photo][:title], post_id: params[:post_id]
    end
    redirect_to post_path(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :check_if_logged_in, except: [:index, :show]

  def new
    @post = Post.new
    @hike = Hike.find params[:hike_id]
  end # new

  def create
    # raise 'hell'
    @post = Post.new post_params
    @post.user_id = @current_user.id
    @post.save
    if params[:file].present?
      response = Cloudinary::Uploader.upload params[:file]
      Photo.create image: response['public_id'], title: params[:photo_title], post_id: @post.id
    end
    redirect_to post_path(@post.id)
  end # create

  def index
    @posts = Post.all.order :title
    redirect_to hikes_path
  end # index

  def show
    @post = Post.find params[:id]
  end # show

  def edit
    @post = Post.find params[:id]
    redirect_to hikes_path unless @post.user == @current_user
  end # edit

  def update
    post = Post.find params[:id]
    if post.user != @current_user
      redirect_to hikes_path
      return
    end

    post.update post_params
    redirect_to post_path(post.id)
  end # update

  def destroy
    @post = Post.destroy params[:id]
    redirect_to hikes_path
  end # destroy

  private

  def post_params
    params.require(:post).permit(:title, :caption, :hike_id)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create

    #1. Check if email address is in the 'users' table
    user = User.find_by email: params[:email]

    #2. Did we find user with that email address (or was it nil), and if we did find user, is the password correct? Present means not nil, not empty. If both conditions are true then credentials are correct
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id

      redirect_to root_path

    # either user is nil or password doesn't match
    else
      flash[:error] = 'Invalid email or password'
      redirect_to login_path
    end # login check

  end # create

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end # destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end # new

  def create
    @user = User.create user_params

    # check whether the above create was successful, i.e. created a row in the uers table, therefore object has id, or if it failed due to data validation error
    if @user.persisted?
      session[:user_id] = @user.id # log in the newly created account automatically
      redirect_to root_path
    else
      # show form again, no redirect
      render :new
    end

  end # create

  def edit
    redirect_to edit_user_path
  end

  def update

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end # user_params

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hikes_helper.rb
module HikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hikes/_form.html.erb
<%= form_for @hike do |f| %>

  <%= f.label :name, 'Name:' %><br>
  <%= f.text_field :name, class: 'form-text-field' %>
  <br>
  <br>

  <%= f.label :description, 'Description:' %><br>
  <%= f.text_area :description, class: 'form-text-area' %>
  <br>
  <br>

  <%= f.submit class:"submit-button" %>

<% end %>

app/views/hikes/edit.html.erb
<div class="page-header">
  <h2>Edit hike: <%= @hike.name %></h2>
</div>

<div class="page-form">
  <%= render partial: 'form' %>
</div>
<br>

app/views/hikes/index.html.erb
<div class="page-header">
  <h2>All Hikes &#129406;</h2>
</div>

<% @hikes_without_posts.each do |hike| %>

  <div class="hike-index-name-container">
    <h3><%= link_to hike.name, hike_path(hike.id) %></h3>
  </div>

  <div class="hike-index-add-post">
    <p><%= link_to 'Add post', new_post_path(hike_id: hike.id) %> to this hike</p>
  </div>

  <hr class="gradient-line">

<% end %>

<% @hikes.each do |hike, posts| %>

  <div class="hike-index-name-container">
    <h3><%= link_to hike.name, hike_path(hike.id) %></h3>
  </div>

  <div class="hike-index-add-post">
    <p><%= link_to 'Add post', new_post_path(hike_id: hike.id) %> to this hike</p>
  </div>

  <div class="hike-index-images-container">
    <% posts.each do |post| %>
      <%= link_to (cl_image_tag post.photos[0].image, :width=>150, :height=>150, :gravity=>"auto", :crop=>"fill", :quality=>90), post_path(post.id) %>
    <% end %>
  </div>

  <hr class="gradient-line">

<% end %>

app/views/hikes/new.html.erb
<div class="page-header">
  <h2>Add new hike &#127811;</h2>
</div>

<div class="page-form">
  <%= render partial: 'form' %>
</div>
<br>

app/views/hikes/show.html.erb
<h2><%= @hike.name %></h2>

<p><%= @hike.description %></p>

<div class="page-header">
  <h3>Latest posts</h3>
</div>

<div class="hike-index-images-container">
  <% @hike.posts.includes(:photos).each do |post| %>
    <% post.photos.each do |photo| %>
      <%= link_to (cl_image_tag photo.image, :width=>150, :height=>150, :gravity=>"auto", :crop=>"fill", :quality=>90), post_path(post.id) %>
    <% end %>
  <% end %>
</div>

<% if @current_user.present? && @hike.user_id == @current_user.id %>
  <br>
  <%= link_to 'Edit hike', edit_hike_path(@hike) %>
  |
  <%= link_to 'Delete hike', hike_path(@hike), method: 'delete' %>
<% end %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yura</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <div class="header-title">
      <h1>Yura</h1>
    </div>

    <ul class="navigation">
      <% if @current_user.present? %>
      <span class="hidden"><li>Hello, <%= @current_user.name %></li></span>
      <li><%= link_to 'Logout', login_path, method: 'delete' %></li>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Add new hike', new_hike_path %></li>
      <% else %>
      <li><%= link_to 'Login', login_path %></li>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Sign up', new_user_path %></li>
      <% end %>
      <li><%= link_to 'View all hikes', hikes_path %></li>
    </ul>

    <%= yield %>

    <div class="dphlai">
      &copy; dphlai 2020
    </div>
  </body>

</html>

app/views/pages/welcome.html.erb
<div class="container">
  <section class="wrapper">
    <div class="divider">
      <% if @current_user.present? %>
      <h2>Welcome back, <%= @current_user.name %>! &#128075;&#127996;</h2>
      <% else %>
      <h2>Hello! Welcome to Yura. &#128075;&#127996;</h2>
      <% end %>
    </div>
  </section>
</div>

<div class="home-copy">
  <p>Be sure to check out all the latest posts by heading over to "View all hikes".</p>
  <p>If you've discovered an amazing new trail or hike, share it with the world via "Add new hike"!</p>
</div>

app/views/posts/_form.html.erb
<%= form_for @post, html: {multipart: true} do |f| %>

  <%= f.hidden_field :hike_id, value: @hike.id %>

  <%= f.label :title, 'Post title:' %><br>
  <%= f.text_field :title, class: 'form-text-field' %>
  <br>
  <br>

  <%= f.label :caption, 'Caption:' %><br>
  <%= f.text_area :caption, class: 'form-text-area' %>
  <br>
  <br>

  <%= label_tag :photo_image, 'Upload image:' %><br>
  <%= cl_image_upload_tag :photo_image %>
  <br>
  <br>

  <%= label_tag :photo_title, 'Photo title:' %><br>
  <%= text_field_tag :photo_title %>
  <br>
  <br>

  <%= f.submit "Upload post", class:"submit-button" %>

<% end %>

app/views/posts/edit.html.erb
<div class="page-header">
  <h2>Edit post: <%= @post.title %></h2>
</div>

<div class="page-form">
<%= form_for @post, html: {multipart: true} do |f| %>

  <%= f.label :title, 'Post title:' %><br>
  <%= f.text_field :title, class: 'form-text-field' %>
  <br>
  <br>

  <%= f.label :caption, 'Post caption:' %><br>
  <%= f.text_area :caption, class: 'form-text-area' %>
  <br>
  <br>

  <%= f.submit "Finish editing", class:"submit-button" %>

<% end %>
</div>
<br>

app/views/posts/index.html.erb
<h2>All posts</h2>

<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post_path(post.id) %>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<div class="page-header">
  <h2>Create new post &#x1F4F7;</h2>
</div>

<div class="page-copy">
  <p>Uploading new post to <em><%= @hike.name %></em></p>
</div>

<div class="page-form">
  <%= render partial: 'form' %>
</div>
<br>

app/views/posts/show.html.erb
<div class="post-show-title">
  <h2><%= @post.title %></h2>
</div>

<div class="post-show-posted-by">
  <p>posted by <%= @post.user.name %></p>
</div>

<div class="post-show-image">
  <% @post.photos.each do |post| %>
    <%= cl_image_tag(post.image, :width=>500, :height=>500, :gravity=>"auto", :crop=>"fill", :quality=>95) %>
    <br>
  <% end %>
</div>

<div class="post-show-caption">
  <p><em><%= @post.caption %></em></p>
</div>

<% if @current_user.present? && @post.user_id == @current_user.id %>
  <div class="page-copy">
    <%= link_to 'Edit post', edit_post_path(@post) %>
  </div>

  <div class="page-copy">
    <%= link_to 'Delete post', post_path(@post), method: 'delete' %>
  </div>

  <hr class="gradient-line">

  <div class="page-copy">
    <p>Add new photo to post:</p>
  </div>

  <div class="page-form">
    <%= form_for Photo.new, html: {multipart: true} do |f| %>
    <%= f.label :title, 'Photo title:' %>
    <br>
    <%= f.text_field :title, class: 'form-text-field' %>
    <br>

    <%= f.label :image, 'Add new image:', class: 'hidden' %>
    <br>
    <%= f.cl_image_upload :image %>
    <%= hidden_field_tag :post_id, @post.id %>
    <br>
    <br>

    <%= f.submit "Upload photo", class:"submit-button"  %>
    <% end %>
  </div>
<% end %>
<br>

app/views/session/new.html.erb
<div class="page-header">
  <h2>Login</h2>
</div>

<div class="page-form">
  <% if flash[:error] %>
  <strong><%= flash[:error] %></strong>
  <br>
  <br>
  <% end %>

  <%= form_tag login_path do %>

  <%= label_tag :email, 'Email:' %><br>
  <%= email_field_tag :email %>
  <br>
  <br>

  <%= label_tag :password, 'Password:' %><br>
  <%= password_field_tag :password %>
  <br>
  <br>

  <%= submit_tag 'Login', class:"submit-button" %>

  <% end %>
</div>
<br>

app/views/users/new.html.erb
<div class="page-header">
  <h2>Create an account</h2>
</div>

<div class="signup-error">
  <% if @user.errors.full_messages.any? %>
    <ul>
      <% @user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
</div>


<div class="page-form">
<%= form_for @user do |f| %>

  <%= f.label :name, 'Username:' %><br>
  <%= f.text_field :name, class: 'form-text-field' %>
  <br>
  <br>

  <%= f.label :email, 'Email:' %><br>
  <%= f.email_field :email, class: 'form-text-field' %>
  <br>
  <br>

  <%= f.label :password, 'Password:' %><br>
  <%= f.password_field :password, class: 'form-text-field' %>
  <br>
  <br>

  <%= f.label :password_confirmation, 'Password confirmation:' %><br>
  <%= f.password_field :password_confirmation, class: 'form-text-field' %>
  <br>
  <br>

  <%= f.submit 'Sign up', class:"submit-button"  %>

<% end %>
</div>
<br>